version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: ashishkingdom/codedev
    container_name: codedev_reverse_proxy
    depends_on:
        - frontend
        - backend
    ports:
      - 80:80
    restart: on-failure

  # frontend
  frontend:
    image: ashishkingdom/codedev-frontend
    container_name: frontend
    depends_on:
        - backend
    # ports:
    #   - 3000:3000
    restart: on-failure


  # backend
  backend:
    image: ashishkingdom/codedev-backend
    container_name: backend
    # ports:
    #   - 8000:8000
    restart: on-failure

