version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: ashishkingdom/codedev
    container_name: codedev_reverse_proxy
    depends_on:
        - frontend
        - backend
    ports:
      - 6969:80
    restart: on-failure

  # frontend
  frontend:
    image: ashishkingdom/codedev-frontend
    container_name: frontend
    depends_on:
        - backend
        - admin
    # ports:
    #   - 3000:3000
    restart: on-failure
  
  # admin
  admin:
    image: ashishkingdom/codedev-admin
    container_name: admin
    depends_on:
        - backend
    # ports:
    #  - 5000:5000
    restart: on-failure
  
  # backend
  backend:
    image: ashishkingdom/codedev-backend
    container_name: backend
    # ports:
    #   - 8000:8000
    restart: on-failure
    environment:
      - DB_URL=sqlite:///codedev.db
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - JWT_ACCESS_KEY=111cdfcc2c38ae9e6b9212bb0361316cc4aadcbabec3d948fb30ebaaaf8d43af

